[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-main = "0.5"
pretty_assertions = "1.4.0"
itertools = "0.12.0"
parse-display = "0.8.2"
derive_more = "0.99.17"
ndarray = "0.15.6"
num = "0.4.1"
